### ISSUE TITLE
Implement sessions so multiple teams can use the board at the same time.

### ISSUE THREAD

**Issue by Tejpbit** [fredagsdeploy/retro-tool#5]
should also do #8

**Comment by juiceit** [comment]
also codes for sessions so no randoms get in

**Comment by Tejpbit** [comment]
Fixed sessions. they're a generated uuid from the server.
Is that enough or do we want to be able to put a password on a session as well?

**Comment by lindskogen** [comment]
We should open another issue if we feel that we need passwords
